# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      branch:
        description: 'Branch to build'
        required: true
      environment:
        type: choice
        description: 'Environment to Deploy'
        required: true
        default: dev
        options: 
        - dev
        - test
        - prod
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Branch: ${{ github.event.inputs.branch }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
