name: CI

on:
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: 'Environment to Deploy'
        required: true
        default: dev
        options: 
        - dev
        - test
        - prod

jobs:
  build:
    name: Call Workflow Template
    uses: ./.github/workflows/test.yml
    with: 
      environment: ${{ github.event.inputs.environment }}
    
