name: CI

on:
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: 'Environment to Deploy'
        required: true
        default: dev
        options: 
        - dev
        - test
        - prod
      run_tests:
        type: boolean
        description: Do you want to run tests?
        required: true
        default: true     

jobs:
  build:
    name: Call Workflow Template
    uses: ./.github/workflows/test.yml
    with: 
      environment: $GITHUB_REF
  test:
    name: Run Tests
    if: ${{ github.event.inputs.run_tests == 'true'}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
         echo "Is Run Test?: ${{ inputs.run_tests }}"
  
